### PR TITLE
Add section on bulk translations

### PR DESCRIPTION
**Pull request by lgibson7**
@PatriLoto and I added a section on bulk translations.

### CODE REVIEW

**Review by llrs — COMMENTED** [review]
Welcome to the R dev guide! Many thanks for your contribution! 
This new section looks simple and easy, it might help to add translations to more languages.

I see you uploaded some images but they don't have an [alt text](https://bookdown.org/yihui/rmarkdown-cookbook/html-accessibility.html). Could you add some text? 

From the linked reference: 
>  the alt text in square brackets, e.g., an informative text.

**Comment by lgibson7** [comment]
Hi @llrs. Please let me know if I should go into more detail in the alt text.

**Comment by llrs** [comment]
I don't think we need more detailed description as the text already describes it well (imho).
Merging now. Thanks @lgibson7 and @PatriLoto !

**Comment by SaranjeetKaur** [comment]
@all-contributors
please add @PatriLoto for content, doc, ideas.

**Pull request merged**
