### PR TITLE
Update GitHub action versions

### PR DESCRIPTION
**Pull request by cjrace**
## Overview

Quick change to update the actions for the rdevguide as I noticed one of the actions was failing.

## Details

https://github.com/r-devel/rdevguide/actions/runs/11049512047/job/30695306589

image

### CODE REVIEW

**Review by jmaspons — APPROVED** [review]
Looks good

**Comment by cjrace** [comment]
> Looks good

Thanks! I don't have permissions to merge this, but happy for anyone else to do that on my behalf

**Comment by SaranjeetKaur** [comment]
@all-contributors
please add @cjrace for infra.

**Comment by SaranjeetKaur** [comment]
@all-contributors
please add @llrs for maintenance.

**Pull request merged**
