### PR TITLE
Fixed broken link for working group

### PR DESCRIPTION
**Pull request by anelda**

### CODE REVIEW

**Comment by llrs** [comment]
Many thanks! We missed this link when we moved the site.

**Comment by llrs** [comment]
@hturner I seem to have lost permissions to merge (edit too?) but I would merge this, and maybe we ( @SaranjeetKaur ?) might need to check for any other remaining link.

**Comment by anelda** [comment]
> Many thanks! We missed this link when we moved the site.

Great pleasure! Maybe just check if the way that I added the link conforms with your style guides? Maybe it should be a relative URL not absolute?

**Comment by llrs** [comment]
I think there is not style guides for the book (yet) as there have been relatively few people modifying it. 

Using relative urls is a nice idea that might solve future problems (or create new ones if the site moves again). I'm not sure it will work but I guess we can try it and see how it goes.

**Comment by hturner** [comment]
I think a relative link will work, so let's try that.

**Comment by hturner** [comment]
@llrs I've given all organization members Maintainer access to this repo now, so you should be able to merge in future.

**Pull request merged**
